# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbd0641095589f580ac8933eb601e62cc2f92cc2509d542c486f85ac37fba7e93921d66fa04e9e2c8ce5deab01fb3c4a63897d66b8d867c684f1c28cb1967938

test:
  secret_key_base: fe6a0f0ff0d8fac972ff58e3d63c40db2b5507029e86a79ac16e1047713ab73d1604100c5635c2b3bad51306166269e17a88903ebbd300ea4e8b76fead3dad53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
